{{- if .Values.serviceMonitor.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "podinfo.fullname" . }}
  labels:
    {{- include "podinfo.labels" . | nindent 4 }}
    release: kube-prometheus-stack  # required for the Prometheus operator to discover this ServiceMonitor
spec:
  selector:
    matchLabels:
      {{- include "podinfo.selectorLabels" . | nindent 6 }}
  endpoints:
    - port: {{ .Values.serviceMonitor.port }}
      path: {{ .Values.serviceMonitor.path }}
      interval: {{ .Values.serviceMonitor.interval }}
{{- end }}
